site_name: DAT Docs
nav:
    - Introduction: 
        - Getting Started: index.md
        - Installation: Installation.md
        - Interface: Interface.md
        - Preferences: Preferences.md
        - Custom Scripts: Custom_Scripts.md
        - Operators: Operators.md
        - About: About.md

    - DAT It!: 
        - Floor It!: Operators/Floor_It.md
        - Scale It!: Operators/Scale_It.md
        - Mirror It!: Operators/Mirror_It.md
        - Shrink It!: Operators/Shrink_It.md
        - Rez It!: Operators/Rez_It.md
        - Map It!: Operators/Map_It.md
        - Light Tools: Operators/Light_Tools.md
    
theme: readthedocs
